### PR TITLE
fix for countries with offset '-0px ...' (Albania, Argentina UAE)

### PR DESCRIPTION
**Pull request by herchu**
Described in issue https://github.com/DavidEGx/bga-arena-scoreboard/issues/3

### CODE REVIEW

**Comment by DavidEGx** [comment]
How did you generate the bookmarlet?

**Comment by herchu** [comment]
> How did you generate the bookmarlet?

With copy/paste here https://caiorss.github.io/bookmarklet-maker (I found in the README or in some comment in the code)

**Comment by DavidEGx** [comment]
Ok, I've asked because the code in the `README.md` didn't match the bookmarlet I generated myself with your updated `src/score.js`.
Looks like you left some `console.log(...)` and those are not in the `src/score.js`.

Anyway, I'll merge and I'm going to add a bin/update_readme script to make this thing easier.

Thanks for the fix!

**Comment by herchu** [comment]
Oh, manual steps... I must have removed my `console.log` and forgot to update the readme later.

If it helps, here is a branch with script to help updating the README in the future https://github.com/herchu/bga-arena-scoreboard/tree/readme-updater

(I can submit as a PR later as I test a bit more... I coded the script for fun but without much testing)

**Comment by DavidEGx** [comment]
Don't worry, I've merged it, added a bin/update_readme script, run the script and commit the whole thing after your commit.

**Pull request merged**
